#ifndef MEM_LAYOUT_H
#define MEM_LAYOUT_H

#define MEM_SIZE_KERNEL_START          ( 0x80000000000ULL )
#define MEM_SIZE_DIRECT_PHYS_TO_VIRT   ( DIRECT_MAP_NUM_PAGES_1GiB * PAGE_SIZE_1GiB )
#define MEM_SIZE_KERNEL_HEAP           ( 0x80000000000ULL )

#define MEM_START_KERNEL_VIRT_SPACE    ( 0xFFFF800000000000ULL )
#define MEM_START_DIRECT_PHYS_TO_VIRT  ( MEM_START_KERNEL_VIRT_SPACE + MEM_SIZE_KERNEL_START )
//#define MEM_START_DIRECT_PHYS_TO_VIRT  ( 0xFFFF880000000000 )
#define MEM_START_KERNEL_HEAP          ( MEM_START_DIRECT_PHYS_TO_VIRT + MEM_SIZE_DIRECT_PHYS_TO_VIRT )

#endif